version: '3.2'

services:
  hafni_bot:
    container_name: hafni_bot
    restart: always
    image: xivilaimax/hafni_bot:latest
    volumes:
      - type: "bind"
        source: "${HOME}/HafniBot/log"
        target: "/log"
      - type: "bind"
        source: "./config"
        target: "/tg_bot/config"
    entrypoint: [ "python3", "-m", "app"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

#  telegram-bot-api:
#    image: aiogram/telegram-bot-api:latest
#    environment:
#      TELEGRAM_API_ID: "6"
#      TELEGRAM_API_HASH: "eb06d4abfb49dc3eeb1aeb98ae0f581e"
#      TELEGRAM_LOCAL: 1
#    volumes:
#      - telegram-bot-api-data:/var/lib/telegram-bot-api
#    networks:
#      - botapi
#
#  nginx:
#    image: nginx:latest
#    volumes:
#      - telegram-bot-api-data:/usr/share/nginx/html/var/lib/telegram-bot-api:ro
#    environment:
#      - NGINX_PORT=80
#    networks:
#      - botapi

#volumes:
#  telegram-bot-api-data:
#
#networks:
#  reverse-proxy:
#    external:
#      name: nginx-revers-proxy
